### ISSUE TITLE
PacketEvent error, coult not reproduce

### ISSUE THREAD

**Issue by hapyl** [hapyl/EternaAPI#187]
```java
[06:24:25 ERROR]: Could not pass event PacketSendEvent to EternaAPI v4.0.2-SNAPSHOT
java.lang.IllegalArgumentException: Unsupported serializer: net.minecraft.network.syncher.EntityDataSerializer$$Lambda/0x000001b2217bfa40@f51b163
	at EternaAPI.jar/me.hapyl.spigotutils.module.reflect.DataWatcherType.of(DataWatcherType.java:95) ~[EternaAPI.jar:?]
	at EternaAPI.jar/me.hapyl.spigotutils.module.reflect.packet.wrapped.WrappedPacketPlayOutEntityMetadata$WrappedDataWatcherValue.<init>(WrappedPacketPlayOutEntityMetadata.java:103) ~[EternaAPI.jar:?]
	at EternaAPI.jar/me.hapyl.spigotutils.module.reflect.packet.wrapped.WrappedPacketPlayOutEntityMetadata$WrappedDataWatcherValueList.<init>(WrappedPacketPlayOutEntityMetadata.java:64) ~[EternaAPI.jar:?]
	at EternaAPI.jar/me.hapyl.spigotutils.module.reflect.packet.wrapped.WrappedPacketPlayOutEntityMetadata.getWrappedDataWatcherValueList(WrappedPacketPlayOutEntityMetadata.java:53) ~[EternaAPI.jar:?]
	at EternaAPI.jar/me.hapyl.spigotutils.module.reflect.glow.GlowingProtocolMetadataListener.handlePacketSendEvent(GlowingProtocolMetadataListener.java:45) ~[EternaAPI.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1112.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:1.21-81-ceeb8c1]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.21.jar:1.21-81-ceeb8c1]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.21.jar:1.21-81-ceeb8c1]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:628) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at EternaAPI.jar/me.hapyl.spigotutils.protocol.PacketInterceptor.workPacket(PacketInterceptor.java:59) ~[EternaAPI.jar:?]
	at EternaAPI.jar/me.hapyl.spigotutils.protocol.PacketInterceptor.write(PacketInterceptor.java:44) ~[EternaAPI.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:879) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:863) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:968) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:856) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:851) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.DefaultChannelPipeline.write(DefaultChannelPipeline.java:1010) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.AbstractChannel.write(AbstractChannel.java:296) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at net.minecraft.network.Connection.doSendPacket(Connection.java:513) ~[paper-1.21.jar:1.21-81-ceeb8c1]
	at net.minecraft.network.Connection.lambda$sendPacket$13(Connection.java:498) ~[paper-1.21.jar:1.21-81-ceeb8c1]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask$$$capture(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:167) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:4.1.97.Final]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by hapyl** [comment]
Add fail-safe to DataWatcherType#of(), should not happen
