### ISSUE TITLE
Tablist error

### ISSUE THREAD

**Issue by hapyl** [hapyl/EternaAPI#245]
ava.lang.IllegalArgumentException: Cannot locate declared field me.hapyl.eterna.module.reflect.nulls.NullPacketListener.connection
[21:14:42 WARN]: 	at org.apache.commons.lang.reflect.FieldUtils.writeDeclaredField(FieldUtils.java:594)
[21:14:42 WARN]: 	at EternaAPI.jar//me.hapyl.eterna.module.reflect.npc.EternaPlayer.setPing(EternaPlayer.java:54)
[21:14:42 WARN]: 	at EternaAPI.jar//me.hapyl.eterna.module.reflect.npc.EternaPlayer.setPing(EternaPlayer.java:61)
[21:14:42 WARN]: 	at EternaAPI.jar//me.hapyl.eterna.module.player.tablist.TablistEntry.setPing(TablistEntry.java:198)
[21:14:42 WARN]: 	at EternaAPI.jar//me.hapyl.eterna.module.player.tablist.EntryList.lambda$append0$3(EntryList.java:169)
[21:14:42 WARN]: 	at EternaAPI.jar//me.hapyl.eterna.module.player.tablist.Tablist.setColumn(Tablist.java:91)

**Comment by hapyl** [comment]
It's been 4 months and I couldn't replicate this bug
